components:
  mnistApp:
    enabled: true
    name: mnist-api
    namespace: mlops
    replicas: 2
    image: edo1997edo/model-api:v6
    imagePullPolicy: IfNotPresent
    env:
      MODEL_NAME: "model-v12"
      EXPERIMENT_NAME: "mnist_classification"
    ports:
      api: 8000
    nodePorts:
      api: 30800
    serviceType: NodePort
    resources:
      requests:
        memory: "512Mi"
        cpu: "500m"
      limits:
        memory: "1Gi"
        cpu: "1000m"
    ingress:                  # 🔹 блок Ingress
      enabled: true
      className: nginx
      hosts:
        - host: mnist-api.local
          port: 8000
